# ============================================================================
# DipMaster Trading System - Global Configuration
# Version: 4.0.0
# Date: 2025-08-16
# ============================================================================

system:
  name: "DipMaster Trading System"
  version: "4.0.0"
  environment: "${DIPMASTER_ENV:development}"  # Override with env var
  timezone: "UTC"
  
  # System-wide timeouts and limits
  timeouts:
    api_request: 30  # seconds
    websocket_connect: 10  # seconds
    database_query: 60  # seconds
    model_inference: 5  # seconds
    
  # Resource limits
  limits:
    max_concurrent_positions: 10
    max_daily_trades: 100
    max_memory_usage_mb: 4096
    max_cpu_usage_percent: 80

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
logging:
  level: "${LOG_LEVEL:INFO}"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  handlers:
    console:
      enabled: true
      level: "INFO"
      format: "detailed"
      
    file:
      enabled: true
      level: "DEBUG"
      path: "logs/dipmaster_{date}.log"
      rotation: "daily"
      retention: 30  # days
      
    structured:
      enabled: true
      format: "json"
      path: "logs/structured/dipmaster_{date}.jsonl"
      
  loggers:
    # Third-party library log levels
    urllib3: "WARNING"
    websockets: "INFO"
    kafka: "WARNING"
    sqlalchemy: "WARNING"

# ============================================================================
# DATA CONFIGURATION
# ============================================================================
data:
  # Data storage paths
  storage:
    base_path: "data"
    market_data: "data/enhanced_market_data"
    features: "data/features"
    models: "data/models"
    results: "results"
    
  # Data quality thresholds
  quality:
    min_data_completeness: 0.95  # 95%
    max_gap_minutes: 5
    min_volume_threshold: 1000  # USD
    
  # Data retention policies
  retention:
    raw_market_data: 365  # days
    processed_features: 180  # days
    model_predictions: 90  # days
    execution_logs: 30  # days

# ============================================================================
# MARKET DATA CONFIGURATION
# ============================================================================
market_data:
  # Primary data sources
  primary_exchange: "binance"
  backup_exchanges: ["okx", "coinbase"]
  
  # Data collection settings
  collection:
    timeframes: ["1m", "5m", "15m", "1h", "4h", "1d"]
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
      - "ADAUSDT"
      - "SOLUSDT"
      - "XRPUSDT"
      
  # Real-time data settings  
  realtime:
    websocket_url: "wss://stream.binance.com:9443/ws"
    reconnect_attempts: 5
    heartbeat_interval: 30  # seconds
    buffer_size: 1000  # messages

# ============================================================================
# FEATURE ENGINEERING CONFIGURATION
# ============================================================================
features:
  # Technical indicators
  technical:
    rsi_periods: [14, 21, 30]
    ma_periods: [7, 14, 21, 50, 200]
    bb_period: 20
    bb_std: 2.0
    
  # Market microstructure
  microstructure:
    volume_periods: [5, 15, 30]
    price_impact_windows: [1, 5, 15]
    liquidity_metrics: true
    
  # Cross-asset features
  cross_asset:
    correlation_window: 60  # days
    regime_detection: true
    sector_analysis: true

# ============================================================================
# MODEL CONFIGURATION
# ============================================================================
models:
  # Ensemble configuration
  ensemble:
    models: ["lightgbm", "xgboost", "catboost"]
    voting_method: "soft"
    weights: [0.4, 0.35, 0.25]
    
  # Model training
  training:
    validation_split: 0.2
    test_split: 0.2
    cross_validation_folds: 5
    hyperparameter_trials: 100
    
  # Model evaluation
  evaluation:
    metrics: ["accuracy", "precision", "recall", "f1", "auc"]
    min_accuracy: 0.65
    min_sharpe_ratio: 1.5
    max_drawdown: 0.15

# ============================================================================
# RISK MANAGEMENT CONFIGURATION
# ============================================================================
risk:
  # Position sizing
  position_sizing:
    default_size_usd: 1000
    max_position_size_usd: 5000
    max_portfolio_exposure: 0.8  # 80% of capital
    
  # Risk limits
  limits:
    max_daily_loss_usd: 500
    max_weekly_loss_usd: 2000
    max_monthly_loss_usd: 5000
    max_correlation: 0.7
    
  # Stop loss and take profit
  stops:
    default_stop_loss: 0.02  # 2%
    default_take_profit: 0.015  # 1.5%
    trailing_stop: true
    max_holding_time_hours: 24

# ============================================================================
# EXECUTION CONFIGURATION
# ============================================================================
execution:
  # Order execution
  orders:
    default_order_type: "market"
    slippage_tolerance: 0.001  # 0.1%
    partial_fill_threshold: 0.9  # 90%
    max_order_retries: 3
    
  # Timing constraints
  timing:
    max_execution_delay_ms: 100
    order_timeout_seconds: 30
    position_refresh_interval: 5  # seconds

# ============================================================================
# MONITORING CONFIGURATION
# ============================================================================
monitoring:
  # Health checks
  health_checks:
    enabled: true
    interval_seconds: 30
    endpoints:
      - "api_health"
      - "database_health"
      - "websocket_health"
      - "model_health"
      
  # Alerting
  alerts:
    enabled: true
    channels: ["email", "webhook"]
    thresholds:
      high_latency_ms: 1000
      error_rate_percent: 5
      memory_usage_percent: 90
      
  # Metrics collection
  metrics:
    enabled: true
    collection_interval: 10  # seconds
    retention_days: 30
    
# ============================================================================
# API CONFIGURATION
# ============================================================================
api:
  # FastAPI settings
  fastapi:
    host: "0.0.0.0"
    port: 8000
    workers: 4
    reload: false  # Set to true in development
    
  # Security settings
  security:
    cors_origins: ["http://localhost:3000"]
    rate_limit_requests: 1000
    rate_limit_window: 3600  # 1 hour
    
  # API versioning
  versioning:
    default_version: "v1"
    supported_versions: ["v1"]

# ============================================================================
# DEVELOPMENT SETTINGS
# ============================================================================
development:
  # Debug settings
  debug: false
  testing: false
  
  # Development tools
  tools:
    profiling: false
    memory_tracking: false
    performance_monitoring: false
    
  # Mock data for testing
  mock_data:
    enabled: false
    symbols: ["BTCUSDT", "ETHUSDT"]
    start_date: "2024-01-01"
    end_date: "2024-12-31"